name: Analyze

on:
  #workflow_dispatch:

  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      binary_name:
        required: true
        type: string
      
jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        # always root
        shell: sudo bash {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:  
          fetch-depth: 1
          # path: temp_repo
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: /root/artifact
      - run: |
          ls -R
          APP_PACKAGE=$(find . -type f \( -name "*.ipa" -o -name "*.apk" \) | head -n 1)
          echo "APP_PACKAGE=$APP_PACKAGE" >> $GITHUB_ENV
    
      - name: Setup
        env:
          APP_PACKAGE: ${{ env.APP_PACKAGE }}
          BINARY_NAME: ${{ inputs.binary_name }}
        run: |
          mkdir -p /root/workspace/
          cd /root/artifact

          7z x $APP_PACKAGE -o./package
          BINARY_PATH=$(find ./package -name "$BINARY_NAME" -print -quit)
          cp $BINARY_PATH /root/workspace/$BINARY_NAME

          
      - name: Analyze
        env:
          BINARY_NAME: ${{ inputs.binary_name }}
        run: |
          # echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          IMAGE_URL="ghcr.io/exhix/rev-genius:9.2"
          echo "::add-mask::$IMAGE_URL"

          echo "Pulling docker..."
          docker pull -q $IMAGE_URL
          echo "Pulling Finished"
          
          docker run -d --name idap --network none \
            -v /root/workspace:/root/workspace \
            -w /opt/ida $IMAGE_URL \
            tail -f /dev/null
          docker exec idap ./idat -B -L"/dev/stdout" /root/workspace/$BINARY_NAME | tee /root/workspace/output.log

      - name: Clean up
        run: |
          # rm /root/workspace/UnityFramework
          
          cp -r /root/workspace /home/workspace
          chmod -R 777 /home/workspace

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: analysis
          path: /home/workspace
          retention-days: 5
