name: Root Execution Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sudo bash {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: temp_repo

      - name: Setup Environment
        run: |
          mkdir -p /root/repo
          cp -r temp_repo/. /root/repo/
          mkdir -p /root/workspace
          
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"

          7z e /root/repo/res/UnityFramework.7z
          mv UnityFramework /root/workspace/
          
      - name: Docker Operations
        run: |
          # echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          #IMAGE_URL="ghcr.io/${{ github.repository_owner }}/your-image:latest"
          IMAGE_URL="ghcr.io/exhix/rev-genius:9.2"
          echo "::add-mask::$IMAGE_URL"

          echo "Pulling docker..."
          docker pull -q $IMAGE_URL
          echo "Pulling Finished"
          
          docker run -d --name idap --network none \
            -v /root/workspace:/root/workspace \
            -w /opt/ida $IMAGE_URL \
            tail -f /dev/null
          docker exec idap ./idat -B -L"/dev/stdout" /root/workspace/UnityFramework | tee /root/workspace/output.log

      - name: Clean up
        run: |
          rm /root/workspace/UnityFramework
          
          cp -r /root/workspace /home/workspace
          chmod -R 777 /home/workspace

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: outcome
          path: /home/workspace
          retention-days: 5
